@Library('docker-shared-lib')_

/* Pipeline */
pipeline {
  agent { label "containerBuilds" }
  options { 
    ansiColor('xterm') 
    disableConcurrentBuilds()
    skipDefaultCheckout true
  }

  environment {
    HOME           = "${WORKSPACE}"
  }

  stages {
    stage ('cleanWs & checkout scm') {
      steps {
        script {
          deleteDir()
          cleanWs()
          checkout scm
        }
      }
    }
    stage ('preparation') {
      steps {
        script {
          env.DOCKERFILES = dockerfiles
          env.GITHUB_REPO        = github_repo.toLowerCase()
        }
      }
    }
    stage('Container build') {
        when {
            allOf {
            expression { dockerfiles }
            branch "master"
            }
        }
        steps {
            script {
                dockerBuild.login()
                dockerBuild.build("arnabdnandy1706/smartdb:latest")
                dockerBuild.push("arnabdnandy1706/smartdb:latest")
            }
        }
    }
  }
  post { 
    always {
      script {
        cleanWs()
      }
    }
  }
}